./src/dm_pkg.sv
./tb/dm_tb_pkg.sv

./common_cells/src/cdc_reset_ctrlr_pkg.sv
./common_cells/src/fifo_v3.sv
./debug_rom/debug_rom.sv
./debug_rom/debug_rom_one_scratch.sv
./src/dmi_cdc.sv
#./src/dmi_bscane_tap.sv
#./src/dmi_test.sv
./src/dm_top.sv
./src/dm_obi_top.sv
./src/dm_csrs.sv
./src/dm_mem.sv
./src/dmi_jtag.sv
./src/dm_sba.sv
./src/dmi_jtag_tap.sv
./src/dmi_intf.sv
#./riscv-dbg/tb/SimJTAG.sv
#./riscv-dbg/tb/jtag_dmi/jtag_intf.sv
#./riscv-dbg/tb/jtag_dmi/tb_jtag_dmi.sv
#./riscv-dbg/tb/jtag_dmi/jtag_test.sv
#./riscv-dbg/tb/mm_ram.sv
#./riscv-dbg/tb/dp_ram.sv
#./riscv-dbg/tb/tb_top.sv
#./riscv-dbg/tb/boot_rom.sv
#./riscv-dbg/tb/tb_top_verilator.sv
#./riscv-dbg/tb/unused/SimDTM.sv
#./riscv-dbg/tb/tb_test_env.sv
#./riscv-dbg/debug_rom/debug_rom.sv
#./riscv-dbg/debug_rom/debug_rom_one_scratch.sv
#./riscv-dbg/sva/dm_csrs_sva.sv
#./riscv-dbg/sva/dm_top_sva.sv
#./riscv-dbg/sva/dm_sba_sva.sv
